[package]
name = "rust-yew-wasm-tutorial"
version = "0.1.0"
authors = ["Okkonen <okko.oikkonen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
